// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	log "kafka/golang-kafka/kafka-consumer/internal/log"
	mock "github.com/stretchr/testify/mock"

	model "kafka/golang-kafka/kafka-consumer/internal/service/messaging/model"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, _a1, records
func (_m *Service) Add(ctx context.Context, _a1 log.Logger, records model.Message) error {
	ret := _m.Called(ctx, _a1, records)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, log.Logger, model.Message) error); ok {
		r0 = rf(ctx, _a1, records)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, _a1
func (_m *Service) Get(ctx context.Context, _a1 log.Logger) ([]*model.Message, error) {
	ret := _m.Called(ctx, _a1)

	var r0 []*model.Message
	if rf, ok := ret.Get(0).(func(context.Context, log.Logger) []*model.Message); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Message)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, log.Logger) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
